# Generated by Django 4.2 on 2023-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
