# Generated by Django 4.2 on 2023-04-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tourguide_city_tourguide_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguide',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='personality_traits',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='state',
        ),
        migrations.AddField(
            model_name='trip',
            name='is_paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='personality_traits',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
