# Generated by Django 4.2 on 2023-04-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tourguide_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguide',
            name='pay_rate',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_paid',
        ),
    ]
