# Generated by Django 4.2 on 2023-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_tourguide_pay_rate_remove_trip_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='bio',
        ),
        migrations.AddField(
            model_name='tourguide',
            name='biography',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
