# Generated by Django 4.2 on 2023-04-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_profile_biography_remove_tourguide_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourguide',
            old_name='biography',
            new_name='bio',
        ),
    ]
