# Generated by Django 4.2 on 2023-04-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_biography_tourguide_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tour_guide',
        ),
    ]
