# Generated by Django 4.2 on 2023-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_trip_num_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
